# set where STIR installed JSON files are
STIR_CONFIG_DIR="${CONDA_PREFIX}/share/STIR-6.4/config"
export STIR_CONFIG_DIR

STIR_DOC_DIR="${CONDA_PREFIX}/share/doc/STIR-6.4"
export STIR_DOC_DIR

# echo "STIR ACTIVATE STIR_CONFIG_DIR TO $STIR_CONFIG_DIR"
