
{% set name = "STIR" %}
{% set version = "4.0.2" %}
{% set sha256 = "e2e80415127fd4af24b012bfd38d4b81e6f9709b3efa367a12b5c14e640e1c98" %}
{% set treehash = "rel_4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ treehash }}.tar.gz
  url: https://github.com/UCL/{{ name }}/archive/{{ treehash }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-skip-KOSMAPOSL-test-for-conda.patch

build:
  skip: true  # [py2k]
  skip: true  # [win and py<36]
  skip: true  # [win and vc<14]
  skip: true  # [osx]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - boost-cpp
    - numpy
    - swig
    - libitk-devel
    - openmp  # [osx]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libitk
    - openmp  # [osx]

test:
  requires:
    - pytest
  imports:
    - stir
  source_files:
    - recon_test_pack
    - src/swig/test/python
  commands:
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name|lower }}   # [osx]
    - cd recon_test_pack
    - ./run_test_simulate_and_recon.sh  # [not win]
    - ./run_test_listmode_recon.sh  # [not win]
    - ./run_test_simulate_and_recon_with_motion.sh  # [not win]
    - ./run_scatter_tests.sh  # [not win]
    - ./run_tests.sh --nointbp  # [not win]
    - ./run_test_zoom_image.sh  # [not win]
    - run_tests  # [win]
    - cd SPECT
    - ./run_SPECT_tests.sh  # [not win]
    - cd ..
    - cd ..
    - pytest src/swig/test/python


about:
  home: http://stir.sourceforge.net/
  license: GPL and LGPL
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Software for Tomographic Image Reconstruction'
  description: |
    STIR is Open Source software for use in tomographic imaging.
    Its aim is to provide a Multi-Platform Object-Oriented framework for all data manipulations in tomographic imaging.
  doc_url: http://stir.sourceforge.net/documentation
  dev_url: https://github.com/UCL/STIR

extra:
  recipe-maintainers:
    - olivierverdier
    - KrisThielemans
    - paskino
    - casperdcl
