
{% set name = "STIR" %}
{% set version = "5.1.1" %}
{% set build_number = 0 %}

{% if cuda_compiler_version != "None" %}
{% set build_number = build_number + 200 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UCL/STIR/archive/refs/tags/rel_{{ version }}.tar.gz
  sha256: 5d85717a0d0137b6d30e0dc22fe718c1fd33873b26ad0be44e8db953fc2bfd31

build:
  number: {{ build_number }}
  skip: true  # [linux and cuda_compiler_version == "10.2"]
  ignore_run_exports:
    - cudatoolkit
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - cmake
    - ninja
    - swig
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - boost-cpp
    - hdf5  # [not win and not osx_arm64]
    - python
    - numpy
    - libitk-devel
    - libitk
    - nlohmann_json
    - libparallelproj
    - root_base  # [not win]
    - zlib  # [win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - __cuda  # [cuda_compiler_version != "None"]

test:
  requires:
    - pytest
  imports:
    - stir
  source_files:
    - recon_test_pack
    - examples
    - src/swig/test/python
  commands:
    - stir_config --config-dir
    - cd recon_test_pack
    - ./run_test_simulate_and_recon.sh  # [not win]
    - ./run_test_listmode_recon.sh  # [not win]
    - ./run_test_simulate_and_recon_with_motion.sh  # [not win]
    - ./run_scatter_tests.sh  # [not win]
    - ./run_tests.sh --nointbp  # [not win]
    - ./run_test_zoom_image.sh  # [not win]
    - ./run_root_GATE.sh  # [not win]
    - run_tests  # [win]
    - cd SPECT
    - ./run_SPECT_tests.sh  # [not win]
    - cd ..
    - cd ..
    - pytest src/swig/test/python


about:
  home: http://stir.sourceforge.net/
  license: Apache-2.0 AND LicenseRef-PARAPET-license
  license_file: LICENSE.txt
  summary: 'Software for Tomographic Image Reconstruction'
  description: |
    STIR is Open Source software for use in tomographic imaging.
    Its aim is to provide a Multi-Platform Object-Oriented framework for all data manipulations in tomographic imaging.
    Check the recipe at https://github.com/conda-forge/stir-feedstock/blob/main/recipe/meta.yaml
    to see which dependencies are included in this conda package.

    This package contains all STIR utilities and Python support. It is built with ITK on all platforms
    and ROOT on Linux and OSX.

  doc_url: http://stir.sourceforge.net/documentation
  dev_url: https://github.com/UCL/STIR

extra:
  recipe-maintainers:
    - KrisThielemans
    - olivierverdier
    - paskino
    - casperdcl
