travis:
  secure:
    BINSTAR_TOKEN: QR6vyeZ+skrwq9CL8I2fOSfarVT96uwQk5hl97uEnH0ZFAUWJyIA1u3Qtaz7c8jKJsZ4ZGDBQWCdjVNNmWGlW4OL4TJs3HgY7CaIINLy54+q9IC1gZ52MpU8MkwZKrzqkFusQA258bC31Sk1Cipvck4L41abbrjOBpNyqSsVFETXPW1QlMBtofJIUp6NFaV8ToAtjfoAG91r2kfSY1RSA+6HjMnOK574LRzlVBSbR8H69UGe/yLWT6rht2tJO+Z8tRF4agXt/L31H8WUbjG1eecO3+8fxZ/sn61cYI2RIGp6q3HWVsO7671bfTQCWVRcjiGJZkp7RwIbFmBOY2aPE1LAzXjb7Br293vxPwP2jjJMJ1Tqe5WGc3hj5VP4U4a8fvzl1D17e3avBd18nBkKn/z5W8GwVXtf+G0iyRwr0NYTuADbFef8OUzOQUH9qak2ScIPP5fvgApR6pGA7JffigiJVr9ftSKtkJXHA/CMlaFzFInTkyPQMERVRX6U7tnFZUROeuKVQKMgqXn+VAD4A9P8BCu0dxJ2j1HdfRup6X1RXAg0r1q34eaT4+JXZ3ircCLxluhzLSajD1k2GCEYfJqfJCAYJrFjOeRE7aCdAUNCuzoGMHWQIIeYgzHCAJ1nyPfimCkQ2Oksd1oelXoN0nAlkdDCiPppWJSdOcE2HlI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
